import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
    en: {
        save: 'Save',
        select_language: 'Select Language',
        delivery_to: 'Delivery to',
        delivery_by: 'Delivery by',
        buttonLabel: 'Click me',
        address_shipping: 'Address Shipping',
        shipping_address: 'Shipping Address',
        additional_info: 'Additional info',
        additional_info_placeholder: 'Write here any additional info',
        character_count: 120,
        monthly_buy: 'I want to buy these items every month',
        delayed_delivery_one:
            'Another order will be generated in your name 28 days from today, our pharmacist will call you to confirm the order.',
        delayed_delivery_two:
            'You can then make any necessary changes to the order if you wish.',
        select_payment_method: 'Select payment method',
        to_be_paid: 'Amount to be paid',
        cash_on_delivery: 'Cash on delivery (COD)',
        alert_notice: 'Notice',
        // HomeBlock
        see_all: 'see all',
        See_all: 'See all',
        view_all: 'view all',
        yt_video_length: 1.38,
        out_of_stock: 'Out of Stock',
        off: 'off',
        // login
        sign_in: 'Sign in to continue',
        verification: 'Verification',
        login_register:
            'Login/Register to make order,access your orders, special offers, health tips and more!',
        by_continuing: 'By continuing you agree to our',
        terms_of_services: ' Terms of services',
        privacy_policy: ' Privacy Policy ',
        and: 'and',
        return_refund: ' Return and Refund Policy.',
        enter_otp: 'Enter the otp sent to ',
        edit: 'Edit',
        resend_code: 'Resend Code',
        continue: 'Continue',
        referral_code: ' Have a referral code?',
        send: 'Send',
        sendOtp: 'Send OTP',
        error: 'Error',
        valid_mobile: 'Please enter a valid 11 digit mobile number.',
        ok: 'OK',
        something_went_wrong:
            'Something went wrong.Contact customer care at 16778.',
        login_with_phone_error: 'Login With Phone Number Error:',
        not_receive_code: `Have't receive the code yet?`,
        enter_phone_number: 'Enter Phone Number',
        enter_email_address: 'Please enter email',
        shop_now: 'Shop Now',
        add: 'Add',
        added: 'Added',
        b2b: 'B2B',
        urgent: 'Urgent',
        cold: 'Cold',
        paid: 'Paid',
        view_less: 'View Less',
        view_more: 'View More',
        cancelOrder: 'Cancel Order',
        order_cancel: 'Cancel Order',
        orderId: 'Order ID',
        has_been_copied: 'has been copied to the clipboard.',
        order_id_copied: 'Order ID Copied',
        orderedAt: 'Order at',
        subtotal: 'Subtotal',
        amountPayable: 'Amount Payable',
        you_will_see_online_payment_opiton_once_packed:
            'You will see online payment option once your order is packed.',
        create_another_order_with_these_items:
            'Create another order with these items',
        create_another_order_with_this_items:
            'Create another order with this item',
        // shipping_address: 'Address Shipping',
        view_order: 'View Order',
        you_are_saving: 'You are saving',
        in_this_order: 'in this order',
        manufactured_by: 'Manufactured by',
        cart_header: 'Shopping Cart',
        cart_not_available: 'Not Available',
        cart_express_delivery: 'Express Delivery',
        cart_regular_delivery: 'Regular Delivery',
        remove: 'Remove',
        are_you_sure_to_remove: 'Are you sure you want to remove ',
        from_cart: 'Are you sure you want to remove ',
        from_cart: 'from cart?',
        no: 'NO',
        yes: 'YES',
        cart_p_cold_status:
            'Sorry this medicine is heat sensitive, so delivery is not available outside Dhaka city.',
        cart_not_allowed_outside_dhaka:
            'This item is not deliverable outside Dhaka.',
        congratulations: 'Congratulations',
        your_order_has_been_placed_successfully:
            'Your order has been placed successfully.',
        you_have_received_cashback_of_tk_from_arogga:
            'You have received a cashback of __AMOUNT__ tk from Arogga. The cashback will be automatically added to your wallet.',
        total_order_amount: 'Total Order Amount',
        start_a_new_order: 'Start A New Order',
        track_order: 'Track Order',
        arogga: 'Arogga',
        estimated_time: 'Estimated Time',
        confirmation_will_be_sent_to_your:
            'Confirmation will be sent to your Arogga App, SMS',
        check_your_phone_notification_or_sms:
            'Check your Arogga App Notification or Phone SMS',
        upload_prescription: 'Upload Prescription',
        add_up_to: 'Add up to 5 images',
        prescription_added_by_you: 'Prescriptions attached by you',
        are_you_sure_to_remove_prescription:
            'Are you sure want to remove this prescription?',
        cancel: 'Cancel',
        change: 'Change',
        one_arogga_representative_will_call_you:
            'One arogga representative will call you shortly for confirming your order. You may receive cashback based on the final order value.',
        customer_service_call:
            'Our customer service will call you to confirm your order and payment amount.',
        apply: 'Apply',

        in_this_order: 'in this order.',
        you_will_receive: 'You will receive ৳',
        cashback_after_delivery: 'cashback after delivery.',
        subtotal_mrp: 'Subtotal (MRP)',
        view_summary: 'View Summary',
        proceed_to_checkout: 'Proceed to Checkout',
        select_your_date_and_time: 'Select Your Date & Time',
        done: 'Done',
        require_prescription:
            'This medicine requires prescription. Please upload your prescription.',
        regular_delivery_note:
            'Regular (24-48 hours) delivery is available for this item. \nNote: If you want to get full order with express (12-24 Hours) delivery please remove this item from the cart or choose a similar item with express marked on it.',
        express_delivery_note:
            'Express (12-24 Hours) delivery is available for this item.',
        express_delivery: 'Express Delivery',
        regular_delivery: 'Regular Delivery',
        rx: 'Rx',
        cancel_requested: 'Cancel Requested',
        delivery_man: 'Delivery Man',
        status: 'Status',
        zone: 'Zone',
        issue_raised: 'Issue Raised',
        order_again: 'Order Again',
        view_details: 'View Details',
        order_summary: 'Order Summary',
        after_you_pay_online:
            'After you pay online, your order will proceed to delivery.',
        pay_online: 'Pay Online',
        or_pay_cash_on_delivery: 'or pay cash on delivery',
        // Orders
        all: 'All',
        confirmed: 'Confirmed',
        delivering: 'Delivering',
        delivered: 'Delivered',
        there_are_no_orders_yet: 'There are no orders Yet !',
        nothing_found: 'Nothing Found',
        total_discount: 'Total Discount',
        // Single Order
        no_order_found: 'No order found',
        your_cart_is_empty: 'Your cart is empty',
        you_havenot_shopped_yet: "You haven't shopped yet",
        prescription_image: 'Prescription Images',
        additional_info: 'Additional info',
        cashabck_of: 'Cashback of ৳',
        rewarded_for_this_order: 'rewarded for this order.',
        download_your_invoice: 'Download your invoice',
        do_you_want_to_cancel: 'Do you want to cancel this order?',
        confirm: 'Confirm',
        request_failed: 'Request failed',
        something_went_wrong_while_loading_your_order:
            'Something went wrong while loading your order please try again.',
        go_back: 'Go Back',
        // PaymentOption
        you_can: 'You can',
        // SingleOrderProductItem
        cold_chain_maintained: '* Cold chain maintained',
        packed: 'Packed',
        waiting: 'Waiting',
        // Checkout
        place_order: 'Place Order',
        pay_online: 'Pay Online',
        select_your_payment_method: 'Select your payment method',
        you_will_be_given_an_option_to_pay:
            'You will be given an option to pay online after order is packed and ready for delivery.',
        // Timeline
        you_can: 'You can',
        or_pay_cash_on_delivery: 'or pay cash on delivery',
        payment_not_yet_received: 'Payment not yet received, you can',
        for_outside_dhaka_delivery: 'For outside Dhaka delivery please',
        here_once_we_received_your_payment:
            'here, once we receive your payment your order will go out for delivery. If we do not receive payment within',
        this_order_will_automatically_be_cancelled:
            'this order will automatically be cancelled.',
        if_you_have_any_query: 'If You Have Any Query,',
        call_us_on: 'Call Us On ',
        phone_number: 16778,
        or: ' or ',
        message_us_on_facebook: 'Message Us On Facebook',
        order_placed: 'Order Placed',
        //** Lab test start */
        ltSampleCollect: 'Collect From',
        ltSearch: 'Search for lab tests and packages',
        ltFrequent: 'Frequently Booked Lab Tests',
        ltIncludes: 'Includes',
        ltAsKnownAs: 'As known as',
        ltBookTest: 'Book Test',
        ltRemoveTest: 'Remove Test',
        ltPatient: 'Patient',
        ltBookFor: 'Book for',
        ltOff: 'Off',
        ltReportIn: 'Report in',
        ltHours: 'hours',
        ltBooked: 'Booked',
        ltTimes: 'times',
        ltBrowseHealth: 'Browse by Health Concern',
        ltPopularPackages: 'Popular Packages',
        ltLifeStylePackage: 'Life Style Packages',
        ltVitalOrgan: 'Checkups Base on Vital Organs',
        ltMenCheckup: 'Recommended Checkups for Men',
        ltWomenCheckup: 'Recommended Checkups for Women',
        ltTest: 'Test',
        ltPackage: 'Package',
        ltDetails: 'Details',
        ltLab: 'Lab',
        ltSampleType: 'Sample Type',
        ltTestRequirements: 'Test Requirements',
        ltTubeType: 'Tube Type',
        ltPackageIncluded: 'Package Included',
        ltDescription: 'Description',
        ltPlain: 'Plain',
        ltShowMore: 'Show More +',
        ltRecommndedForYou: 'Recommended for You',
        ltSuggestion: 'Showing suggestions for ',
        ltNothingShow: 'Nothing to show here!',
        ltNothingLoad: 'Nothing more to load!',
        ltMyLabTest: 'My Lab Test',
        ltMyOrders: 'My Orders',
        ltMyReports: 'My Reports',
        ltManagePatients: 'Manage Patients',
        ltOrder: 'Order',
        ltDate: 'Date',
        ltSchedule: 'Schedule',
        ltOrderDetails: 'Order Details',
        ltPatientReports: 'Patient Reports',
        ltManagePatient: 'Manage Patient',
        ltEditPatient: 'Edit Patient',
        ltPaid: 'Paid',
        ltNotPaid: 'Not Paid',
        ltCOD: 'COD',
        ltOnlinePayment: 'Online Payment',
        ltNote: 'Note',
        ltSampleCollectionAdderss: 'Sample Collection Address',
        ltPaymentDetails: 'Payment Details',
        ltSubTotal: 'Subtotal',
        ltDiscountApplied: 'Discount Applied',
        ltCouponApplied: 'Coupon Applied',
        ltAroggaCashApplied: 'Arogga Cash Applied',
        ltRoundingOff: 'Rounding Off',
        ltSampleCollectionCharge: 'Sample Collection Charge',
        ltHardCopyCharge: 'Hard Copy Charge (Optional)',
        ltYouPaid: 'You paid',
        ltYouPay: 'You pay',
        ltOrderDate: 'Order Date',
        ltPatientName: 'Patient Name',
        ltWeight: 'Weight',
        ltGender: 'Gender',
        ltAge: 'Age',
        ltRelationShip: 'RelationShip',
        ltSaveChanges: 'Save Changes',
        ltUploadPhoto: 'Upload Photo',
        ltTotalPayable: 'Total Payable',
        ltTotal: 'Total',
        ltProceedToCheckout: 'Proceed to Checkout',
        ltChange: 'Change',
        ltAddAddress: 'Add Address',
        ltCheckout: 'Checkout',
        ltSampleCollectionSchdule: 'Sample Collection Schedule',
        ltWriteAdditionalInfo: 'Write here any additional info',
        ltSelectSchedule: 'Select Schedule',
        ltHardCopyOfReport: 'Hard Copy of Report',
        ltAmountToBePaid: 'Amount to be Paid',
        ltPlaceOrder: 'Place Order',
        ltCodAvailableInDhaka:
            'Cash on delivery option is only available for Dhaka',
        ltHardCopyDeclaimer:
            'Report wil be delivered within 3-4 working days. Hard Copy charges are non-refundable once the reports have been dispatched',
        ltCongratulations: 'Congratulations',
        ltOrderRecived: 'Your Order Added Successfully',
        ltStartNewOrder: 'Start a new order',
        ltCancelBooking: 'Cancel Order',
        ltPayNow: 'Pay Now',
        //** Lab test end */
        // HomeHeader
        wholesale: 'Wholesale',
        loading: 'Loading',
        choose_address: 'Choose Address',
        search_for: 'Search for',
        medicine: 'medicine',
        healthcare_items: 'healthcare items',
        wellness: 'wellness',
        // ProductDetails
        show_more: 'Show more',
        show_less: 'Show less',
        express_available: 'Express Available',
        buy_drugs_at_wholesale_price:
            'Register to buy drugs at wholesale prices for your pharmacy',

        register: 'Register',
        people_recently_viewed_this: 'people recently viewed this.',
        original_product: '100% Original Product',
        off: 'off',
        brand: 'Brand',
        generic: 'Generic:',
        choose: 'Choose',
        additional_offers: 'Additional Offers',
        alternative_brands_for: 'Alternative Brands for',
        sort: 'Sort',
        price: 'Price',
        relevance: 'Relevance',
        medicine_overview: 'Medicine Overview',
        quick_tips: 'Quick Tips',
        brief_description: 'Brief Description',
        faqs: 'FAQs',
        disclaimer: 'Disclaimer',
        the_information_provided_herein:
            'The information provided herein is accurate, updated and complete as per the best practices of the Company. ',
        please_note_that_this_information:
            ' Please note that this information should not be treated as a replacement for physical medical consultation or advice. We do not guarantee the accuracy and the completeness of the information so provided. The absence of any information and/or warning to any drug shall not be considered and assumed as an implied assurance of the Company. We do not take any responsibility for the consequences arising out of the aforementioned information and strongly recommend you for a physical consultation in case of any queries or doubts.',
        visit_store: 'Visit Store',
        view_cart: 'View Cart',
        add_to_cart: 'Add to Cart',
        cart_products: 'Products',
        requesting: 'Requesting',
        request_sent: 'Request Sent',
        request_stock: 'Request Stock',
        select_quantity: 'Select Quantity',
        added_to_your_cart: 'Added to your cart',
        favorites: 'Favorites',
        how_does_arogga_collect_medicine: 'How does Arogga collect medicine?',
        counterfeit_and_substandard_medicines_are_a_big_problem:
            'Counterfeit and substandard medicines are a big problem for Bangladesh, so to overcome this problem, all our medicines are purchased directly from the company.\n\nArogga does not procure medicines from any wholesalers, so there is no chance of counterfeit medicines in our stock.\n\nSince every medicine comes directly from the pharmaceutical company, you can be 100% sure about the medicine purchased from us.\n\nThe chance of counterfeit medicine exists when one procures the medicine from a source other than the company.',
        prescription_required: 'Prescription Required',
        this_medicine_requires_prescription:
            'This medicine requires prescription. Please upload your prescription.',
        request_for_medicine: 'Request for medication',
        sorry_the_product_is_not_in_our_stock:
            'Sorry the product is not in our stock at the moment, you can request for the product if you want. By clicking the Request Stock button.\n\nIn that case, you will be informed through notification whenever the product comes in stock.',
        this_product_uses_heat_sensitive_boxes:
            'This product uses heat sensitive boxes to transport.',
        this_product_will_be_delivered_in_Dhaka_city_only:
            'This product will be delivered in Dhaka city only.',
        this_product_can_be_ordered_from_all_over_bangladesh:
            'This product can be ordered from all over Bangladesh.',

        // MyAccount
        notification: 'Notification',
        notification_details: 'Notification Details',
        my_order: 'My Order',
        my_prescriptions: 'My Prescriptions',
        request_medicine: 'Request Medicine',
        my_favorite: 'My Favourite',
        manage_address: 'Manage Address',
        payment_history: 'Payment History',
        refer_and_earn: 'Refer and Earn',
        rate_us: 'Rate us',
        terms_and_conditions: 'Terms & Conditions',
        privacy_policy: ' Privacy Policy ',
        payment_terms: 'Payment Terms',
        faq: 'FAQ',
        about_us: 'About us',
        contact_us: 'Contact us',
        my_profile: 'My Profile',
        sign_in_with_icon: 'Sign in →',
        view_profile: 'View Profile',
        arogga_cash: 'Arogga Cash: ',
        call_for_order: 'Call for Order',
        legal_and_support: 'Legal & Support',
        sign_out: 'Sign Out',
        are_you_sure_you_want_to_sign_out: 'Are you sure you want to Sign Out?',
        something_went_wrong_try_again_later:
            'Something went wrong! Try again later',
        my_account: 'My Account',
        app_camera_permission: 'App Camera Permission',
        app_needs_access_to_your_camera: 'App needs access to your camera',
        ask_me_later: 'Ask Me Later',
        camera_permission_required: 'Camera permission required!',
        name: 'Name',
        date_of_birth: 'Date of Birth',
        gender: 'Gender',
        district: 'District',
        not_found: 'Not-Found',
        phone: 'Phone Number',
        email: 'Email Address',
        edit_profile: 'Edit Profile',
        return_and_refund_policy: ' Return and Refund Policy',
        health_tips: 'Health Tips',
        // ImageGallery
        prescription_downloaded_successfully:
            'Prescription downloaded successfully',
        permission_required: 'Permission required!',
        storage_permission: 'Storage Permission',
        storage_permission_is_required: 'Storage permission is required',
        ask_me_later: 'Ask Me Later',
        // ImageUploaderSheet
        upload_avatar: 'Upload Avatar',
        camera: 'Camera',
        library: 'Library',
        // Header
        notifications: 'Notifications',
        my_orders: 'My Orders',
        product_reviews:'Product Review',
        rider_review:'Rider Review',
        // MyPrescription
        camera_not_available: 'Camera not available',
        something_went_wrong_only: 'Something went wrong',
        are_you_sure_to_delete_prescription:
            'Are you sure you want to delete prescription?',
        no_prescription_found: 'No Prescription Found',
        tap_to_select: 'Tap to select',
        attach_prescription: 'Attach Prescription',
        maximum_five_prescription_can_be_selected:
            'Maximum 5 prescription can be selected',
        // Prescriptions
        add_prescriptions: 'Add Prescription',
        no_prescription_selected: 'No prescription selected',
        prescriptions: 'Prescriptions',
        your_attached_perscription_will_be_secure:
            'Your attached prescription will be secure and private. Only our pharmacist will review it.',
        valid_prescription_guide: 'Valid Prescription Guide',
        include_details_of_doctor_and_patient:
            'Include details of doctor and patient+clinic visit details.\n\nMedicines will be dispensed as per prescription.',
        why_upload_the_picture_of_the_prescription:
            'Why upload the picture of the prescription?',
        prescription_will_be_secure_and_private:
            'Your attached prescription will be secure and private as only our pharmacists will review it.',
        your_are_free_from_the_fear_of_losing_prescriptions:
            'You are free from the fear of losing prescriptions, you can find your digital prescriptions in Arogga app for life.',
        no_problem_if_you_cannot_understand_doctors_handwriting:
            "No problem if you can't understand the doctor's handwriting, our 'A' Grade Pharmacist will assist you in ordering the medicine by viewing the prescription.",
        your_perscription_will_never_be_shared_with_any_third_party:
            'Your prescription will never be shared with any third party.',
        according_to_bangladesh_government:
            'According to Bangladesh government regulations, prescription is mandatory for ordering some medicines.',
        gallery: 'Gallery',
        pdf_doc: 'Pdf Doc',
        // Refer
        no_share_no_care: 'No Share! No Care!',
        sorry_you_havenot_share_with_anyone:
            'Sadly you haven’t shared with anyone!! Share now and keep earning for lifetime.',
        share: 'Share',
        arogga_referral_code: 'Arogga referral code',
        order_medicine_at_home_from_arogga:
            'Order medicines at home from Arogga app.\nRefer code:',
        app_download_link: '\nApp Download Link',
        success: 'Success',
        request_failed: 'Request Failed',
        order_medicines_and_healthcare_products_from_the_comfort_of_your_home:
            'Order Medicines and Healthcare Products from the comfort of your home from Arogya App..\nGet Delivery within 12-48 Hours\nRefer Code:',
        enter_the_above_code_while_logging_in_or_install:
            '\nEnter the above code while logging in or install the Aarogya app from the link below.',
        invite_friends_earn_money: 'Invite friends. Earn money.',
        tell_a_friend_about_arogga_and_get:
            'Tell a friend about Arogga and get',
        taka: 'taka',
        reward: 'reward',
        your_referral_code: 'Your referral code:',
        enter_refer_code: 'Enter Refer Code',
        redeem: 'Redeem',
        share_with_friends: 'Share With Friends',
        you_will_get: 'You will get',
        taka_each_time_your_friends_join_with_your_referral_code:
            'Taka each time your friends join with your referral code and place their first order. Make sure they enter this code while signing up for arogga.',
        your_referral_code_is_valid_for_lifetime:
            '*Your referral code is valid for lifetime.',
        // PharmacyRegistration
        pharmacy_registration: 'Pharmacy Registration',
        b2b_registration: 'B2B Registration',
        full_name: 'Full Name',
        enter_full_name: 'Enter full name',
        mobile_number: 'Mobile Number',
        enter_mobile_number: 'Enter Mobile Number',
        pharmacy_name: 'Pharmacy Name',
        others_name: 'Others Name',
        enter_your_pharmacy_name: 'Enter your pharmacy name',
        enter_your_business_name: 'Enter your Business name',
        drug_license_number: 'Drug License Number',
        trade_license_number: 'Trade License Number',
        enter_your_drug_license_number: 'Enter your drug license number',
        enter_your_trade_license_number: 'Enter your trade license number',
        upload_drug_license: 'Upload Drug License',
        upload_trade_license: 'Upload Trade License',
        submit: 'Submit',
        all_the_fields_are_required: 'All the fields are required',
        is_required: 'is required',
        invalid_mobile_number: 'Invalid Mobile Number',
        successful: 'Successful',
        failed: 'Failed',
        my_profile: 'My Profile',
        // Edit Profile
        update_profile: 'Update Profile',
        gender: 'Gender',
        select_gender: 'Select Gender',
        date_of_birth: 'Date of Birth',
        save_changes: 'Save Changes',
        male: 'Male',
        female: 'Female',
        date_picker: 'Date Picker',
        profile_updated_successfully: 'Profile updated Successfully',
        please_enter_a_valid_email_address:
            'Please enter a valid email address.',
        type_name_at_least_three_characters: 'Type name at least 3 characters.',
        // Brand
        brand_list: 'Brand List',
        no_brand_available: 'No Brand Available',
        there_are_no_brands_available: 'There are no Brands Available',
        // SuggestMediciine
        reqeust_medicine: 'Request medicine',
        medicine_name: 'Medicine Name',
        enter_medicine_name: 'Enter medicine name',
        strength: 'Strength',
        strength_sign: 'i.e 10mg',
        medicine_form: 'Medicine Form',
        medicine_form_sign: 'i.e Tablet',
        company: 'Company',
        company_sign: 'i.e Square Pharmaceuticals Ltd.',
        upload_file: 'Upload File',
        optional: '(Optional)',
        if_you_want_to_suggest_multiple_medicines:
            'If you want to suggest multiple products, please email Excel sheet to info@arogga.com',
        suggest: 'Suggest',
        name_strength_and_form_are_requierd:
            'Product Name and Types are required',
        product_name_is_required: 'Product Name is required',
        product_suggested: 'Product Suggested',
        medicine: 'Medicine',
        beauty: 'Beauty',
        healthcare: 'Healthcare',
        product_name: 'Product Name',
        enter_product_name: 'Enter product name',
        type: 'Type',
        select_product_type: 'Select product type',
        form: 'Form',
        select_company_name: 'Select Company Name',
        enter_medicine_name: 'Enter medicine name',
        // Help
        hi_what_can_we_help_you_with: 'Hi , what can we help you with?',
        faqs: 'FAQs',
        for_more_info_call_now: 'For More Info Call Now',
        // Blogs
        health_tips_details: 'Health Tips Details',
        read_more: 'Read more',
        // SingleBlog
        share_this_tips_wth_friends: 'Share this tips with friends',
        recommended_topics: 'Recommended topics',
        leave_a_comment: 'Leave a comment',
        comment: 'Comment',
        share_your_thoughts: 'Share your thoughts',
        comments: 'comments',
        was_this_post_helpful: 'Was this post helpful?',
        share_your_thoughts: 'Share your thoughts',
        // CategoryListing
        sort_by: 'Sort by',
        filters: 'Filters',
        // Addresses
        adddress: 'Address',
        current_shipping_address: '(Shipping Address)',
        nothing_more_to_load: 'Nothing more to load!',
        add_new_address: 'Add New Address',
        delete: 'Delete',
        manage_address: 'Manage Address',
        // Addaddress
        please_enter_valid_phone_number:
            'Please enter a valid 11 digit mobile number.',
        enter_your_valid_address: 'Enter your valid address',
        add_shipping_address: 'Add shipping address',
        country_code: '+88',
        region: 'Region',
        select_region: 'Select Region',
        city: 'City',
        select_city: 'Select City',
        area: 'Area',
        select_area: 'Select area',
        type_house_flat_no_road: 'Type House, Flat No, Road',
        address_type: 'Address Type',
        make_default_address: 'Make default address',
        save_address: 'Save Address',
        phone_number_text: 'Phone Number',
        // ProductListing
        all_products: 'All Products',
        products: 'products',
        // WishList
        tags: 'Tags:',
        manage_tags_to: 'Manage tags to...',
        new_tags: 'New tags',
        enter_tag_name: 'Enter tag name',
        add_tag: 'Add Tag',
        choose_clor_for_this_tag: 'Choose color for this tag:',
        this_product_is_already_tagged: 'This product is already tagged',
        no_favorite_yet: 'No wishlist Yet',
        you_havent_marked_any_favorite:
            'You haven’t marked any items in wishlist',
        there_are_no_tags_on_this_product: 'There are no tags on this product!',
        other_tag: 'Other Tags :',
        tag_name_should_be_at_least_two_characters:
            'Tag name should be at least 2 characters',
        are_you_sure_to_remove_this_item_from_wishlist:
            'Are you sure you want to remove this item from wishlist?',
        // CompanyList
        search_company: 'Search Company',
        // HomeCategoryModal
        categories: 'Categories',
        top_brands: 'Top Brands',
        shop_by_categories: 'Shop By Categories',
        general_discount: 'General Discount',
        cancelled: 'Cancelled',
        total_additions: 'Total Additions',
        // mixed
        go_to_home: 'Go To Home',
        sorry_we_can_not_find_your_orders:
            'Sorry! We can not find your orders!',
        // Vendor
        no_product_is_available: 'No Product is available',
        product_list: 'Proudct List:',
        purchase_order_list: 'Purchase Order List',
        purcase_order_id: ' Purchase Order ID:',
        upload_prescription: 'Upload Prescription',
        upload_profile_photo: 'Upload Profile Photo',
        special_offers: 'Special Offers',
        we_will_notify_you: 'We will notify you!',
        added_successfully: 'Added successfully!',
        you_already_requested_this_product:
            'You already requested this product!',
        orders: 'Orders',
        notified_products: 'Notified Products',
        suggested_products: 'Suggested Products',
        wishlist: 'Wishlist',
        labtest: 'Lab Test',
        vendor_dashboard: 'Vendor Dashboard',
        transaction_history: 'Transaction History',
        logout: 'Logout',
        we_are_hiring: 'We are hiring',
        all_brand: 'All Brand',
        select_address: 'Select Address',
        proceed_to_checkout: 'Proceed to Checkout',
        date: 'Date',
        subarea: 'Sub area',
        notify: 'Notify',
        all_products: 'All Products',
        you_didnot_request_any_products: 'You did not requested any products!',
        this_product_is_not_available_right_now:
            'This product is not available right now. We will notify you when it is available.',
        view_requested_items: 'View Requested Items',
        deleted_successfully: 'Deleted successfully',
        currently_this_product_not_available:
            'Currently this product not available',
        this_product_is_currently_out_of_stock_please:
            'This product is currently out of stock. Please click on notify if you want to get updated once it is available!',
        no_product_found: 'No Product Found',
        yay_you_have_seen_it_all: 'Yay! you have seen it all!',
        replacement_products_for: 'Replacements Products for',
        no_products_found_for_replacement: 'No products found for replacement',
        packed: 'Packed',
        we_are_waiting_for_this_item_to_be_packed:
            'We are waiting for this item to be packed.',
        this_item_is_already_packe_cannot_be_edited_anymore:
            'This item is already packed, can’t be edited anymore.',
        replace_with_alternative_item: 'Replace with alternative item',
        replace: 'Replace',
        are_you_sure_to_delete_this_product:
            'Are you sure to delete this product',
        product_deleted_successfully: 'Product deleted successfully!',
        vendor_dashboard: 'Vendor Dashboard',
        suggest_products: 'Suggest Products',
        company_name: 'Company Name',
        company_name_example: 'i.e Cerave, Square Pharmaceuticals',
        upload_image: 'Upload Image',
        medicine_products: 'medicine products',
        healthcare_products: 'healthcare products',
        beauty_products: 'beauty products',
        address_deleted_successfully: 'Address deleted successfully!',
        confirm_default_address: 'Confirm Default Address',
        are_you_sure_to_make_this_address_default:
            'Are you sure to make this address default?',
        no_address_found: 'No Address Found',
        you_have_not_added_your_address: 'You have not added your address',
        no_notification: 'No Notification!',
        we_have_not_any_notification_for_you:
            'We haven’t any notification for you',
        mark_as_read: 'Mark as Read',
        notifications_unread: 'Notifications Unread',
        suggest_products: 'Suggest Products',
        lab_tests: 'Lab Tests',
        add_up_to_five_mb: 'Add up to 5 MB',
        verify: 'Verify',
        arogga_cash_applied: 'Arogga Cash Applied',
        arogga_bonus_applied: 'Arogga Bonus Applied',
        app_version: 'App Version',
        log_in_or_register_to_view_your_complete_profile:
            'Log in or Register to view your complete profile',
        no_blogs_found: 'No blogs Found!',
        we_have_not_any_blog_from: 'we haven’t any blog from',
        your_reply_sent_successfully: 'Your Reply sent Successfully!',
        your_comment_sent_successfully: 'Your Comment sent Successfully!',
        new: 'new',
        easily_order_by_your_prescription: 'Easily Order by your prescription',
        upload_your_perscription_picture:
            'upload your prescription pic and we will do the rest',
        trending_product_is_loading: 'Trending product is loading',
        purchase_order_items_list: 'Purchase Order Items List:',
        withdraw_your_fund: 'Withdraw Your Fund',
        please_select_your_withdrawl_method:
            'Please select your withdrawl method to withdraw your fund.',
        product_description: 'Product Description',
        recent_searches: 'Recent Searches',
        clear_recent_searched_items: 'Clear Recent Searched Items',
        are_you_sure_to_clear_recent_searched_items:
            'Are you sure to clear rececnt searched items',
        clear: 'Clear',
        did_not_match_any_medicine:
            ' did not match any medicine, healthcare, beauty products or lab test',
        suggestions: 'Suggestions:',
        make_sure_that_all_words_are_spelled_correctly:
            'Make sure that all words are spelled correctly',
        try_different_keywords: 'Try different keywords',
        try_more_general_keywords: 'Try more general keywords',
        or_capital: 'Or',
        options: ' option.',
        you_can_request_us_to_add_medicine:
            'You can request us to add medicine/healthcare products by',
        your_search: 'Your search',
        showing_suggestions_for: 'Showing suggestions for',
        business_type: 'Business Type',
        select_business_type: 'Select Business Type',
        you_may_also_like: 'You May Also Like',
        name_is_required: 'Name is required',
    },
    bn: {
        save: 'সেভ করুন',
        select_language: 'ভাষা নির্বাচন',
        delivery_to: 'ডেলিভারি',
        delivery_by: 'Delivery by',
        buttonLabel: 'Click me',
        address_shipping: 'ঠিকানা',
        shipping_address: 'ঠিকানা',
        additional_info: 'অতিরিক্ত তথ্য লিখুন',
        additional_info_placeholder: '',
        character_count: 120,
        monthly_buy: 'আমি প্রতি মাসেই কিনতে চাই',
        delayed_delivery_one:
            'আজ থেকে ২৮ দিন পরে আপনার নামে আরেকটি অর্ডার তৈরী হবে, আমাদের ফার্মাসিস্ট আপনাকে ফোন করে অর্ডারটি কনফার্ম করবেন।',
        delayed_delivery_two:
            'আপনি তখন চাইলে যেকোন পরিবর্তন করে নিতে পারবেন ওই অর্ডারে।',
        select_payment_method: ' পেমেন্টের পদ্ধতি নির্বাচন করুন',
        to_be_paid: 'পরিশোধ করতে হবে',
        cash_on_delivery: 'পণ্য হাতে পেয়ে টাকা পরিশোধ করুন',
        alert_notice: 'নোটিশ',
        // HomeBlock
        see_all: 'সবগুলো দেখুন',
        See_all: 'সবগুলো দেখুন',
        view_all: 'সবগুলো দেখুন',
        yt_video_length: 1.38,
        out_of_stock: 'স্টকে নেই',
        off: 'off',
        // login
        sign_in: 'চালিয়ে যেতে সাইন ইন করুন',
        verification: 'প্রতিপাদন',
        login_register:
            'অর্ডার করতে লগইন/রেজিস্টার করুন, আপনার অর্ডার, বিশেষ অফার, স্বাস্থ্য টিপস এবং আরও অনেক কিছু !',
        by_continuing:
            'চালিয়ে যাওয়ার মাধ্যমে আপনি আমাদের সাথে সম্মতি প্রকাশ করেছেন',
        terms_of_services: ' পরিষেবা শর্তাবলী',
        privacy_policy: ' গোপনীয়তা নীতি ',
        and: 'এবং',
        return_refund: ' রিটার্ন এবং রিফান্ড নীতি।',
        enter_otp: 'পাঠানো otp লিখুন',
        edit: 'পরিবর্তন',
        resend_code: 'কোড পুনরায় পাঠান',
        continue: 'চালিয়ে যান',
        referral_code: ' Have a referral code?',
        send: 'পাঠান',
        sendOtp: 'ওটিপি পাঠান',
        error: 'Error',
        valid_mobile: '১১ ডিজিটের মোবাইল নম্বর লিখুন।',
        ok: 'OK',
        something_went_wrong:
            'কিছু ভুল হয়েছে। ১৬৭৭৮ নাম্বারে কাস্টমার কেয়ারে যোগাযোগ করুন।',
        login_with_phone_error: 'ফোন নাম্বার দিয়ে লগইনে ত্রুটি হচ্ছে ',
        not_receive_code: `কোডটি এখনো পৌঁছেনি?`,
        enter_phone_number: 'ফোন নাম্বার লিখুন',
        enter_email_address: 'ইমেল ঠিকানা লিখুন',
        shop_now: 'এখনই কিনুন',
        add: 'যুক্ত করুন',
        added: 'যুক্ত হয়েছে',
        b2b: 'B2B',
        urgent: 'জরুরি',
        cold: 'ঠান্ডা',
        paid: 'পরিশোধিত',
        view_less: 'কম দেখুন',
        view_more: 'আরও দেখুন',
        cancelOrder: 'অর্ডার বাতিল করুন',
        order_cancel: 'অর্ডার বাতিল করুন',
        orderId: 'অর্ডার আইডি',
        has_been_copied: 'ক্লিপবোর্ডে কপি করা হয়েছে।',
        order_id_copied: 'অর্ডার আইডি কপি করা হয়েছে',
        orderedAt: 'অর্ডার করা হয়েছে',
        subtotal: 'মোট',
        amountPayable: 'প্রদানযোগ্য অর্থের পরিমাণ',
        you_will_see_online_payment_opiton_once_packed:
            'আপনি অনলাইন পেমেন্ট করার পর, আপনার অর্ডারটি ডেলিভারিতে যাবে',
        create_another_order_with_these_items:
            'এই আইটেম গুলি দিয়ে আরেকটি অর্ডার তৈরি করুন',
        create_another_order_with_this_items:
            'এই আইটেম গুলি দিয়ে আরেকটি অর্ডার তৈরি করুন',
        shipping_address: 'ঠিকানা',
        view_order: 'অর্ডারগুলো দেখুন',
        you_are_saving: 'আপনি সাশ্রয় করছেন',
        in_this_order: 'এই অর্ডারে',
        manufactured_by: 'তৈরি করেছে',
        cart_header: 'Shopping Cart',
        cart_not_available: 'এখন পাওয়া যাচ্ছে না',
        cart_express_delivery: 'এক্সপ্রেস ডেলিভারি',
        cart_regular_delivery: 'নিয়মিত ডেলিভারি',
        remove: 'অপসারণ',
        are_you_sure_to_remove: 'আপনি নিশ্চিত যে আপনি অপসারণ করতে চান ',
        from_cart: 'আপনি নিশ্চিত যে আপনি অপসারণ করতে চান ',
        from_cart: 'কার্ট থেকে?',
        no: 'না',
        yes: 'হ্যা',
        cart_p_cold_status:
            'দুঃখিত এই মেডিসিনটি তাপ সংবেদনশীল, তাই ঢাকা শহরের বাইরে আপাতত ডেলিভারি হচ্ছে না।',
        cart_not_allowed_outside_dhaka:
            'এই পণ্যটি ঢাকার বাইরে সরবরাহযোগ্য নয়।',
        congratulations: 'অভিনন্দন',
        your_order_has_been_placed_successfully:
            'আপনার অর্ডার সফলভাবে স্থাপন করা হয়েছে।',
        you_have_received_cashback_of_tk_from_arogga:
            'আপনি Arogga থেকে __ টাকা ক্যাশব্যাক পেয়েছেন। ক্যাশব্যাকটি স্বয়ংক্রিয়ভাবে আপনার ওয়ালেটে যোগ করা হবে।',
        total_order_amount: 'সর্বমোট অর্ডার পরিমাণ',
        start_a_new_order: 'নতুন অর্ডার শুরু করুন',
        track_order: 'অর্ডার ট্র্যাক করুন',
        arogga: 'আরোগ্য',
        estimated_time: 'আনুমানিক সময়',
        confirmation_will_be_sent_to_your:
            'নিশ্চিতকরণ তথ্য আপনার আরোগ্য অ্যাপ অথবা এসএমএস এ পাঠানো হবে।',
        check_your_phone_notification_or_sms:
            'আপনার আরোগ্য অ্যাপ নোটিফিকেশন অথবা ফোনের এসএমএস চেক করুন।',
        upload_prescription: 'ঔষধ নির্দেশিকা আপলোড করুন',
        add_up_to: 'সর্বোচ্চ ৫টি ছবি যুক্ত করুন',
        prescription_added_by_you: 'আপনি ঔষধ নির্দেশিকা সংযুক্ত করেছেন',
        are_you_sure_to_remove_prescription:
            'আপনি নিশ্চিত যে আপনি এই নির্দেশিকা সরানো চান?',
        cancel: 'বাতিল',
        change: 'পরিবর্তন',
        one_arogga_representative_will_call_you:
            'আরোগ্য থেকে একজন প্রতিনিধি শীঘ্রই আপনার অর্ডার নিশ্চিত করতে আপনাকে কল করবেন। আপনি চূড়ান্ত অর্ডার মূল্যের ভিত্তিতে ক্যাশব্যাক পাবেন।',
        apply: 'আবেদন',

        in_this_order: 'এই অর্ডারে.',
        you_will_receive: 'আপনি পাবেন ৳',
        cashback_after_delivery: 'ডেলিভারির পরে ক্যাশব্যাক পাবেন।',
        subtotal_mrp: 'মোট (MRP)',
        view_summary: 'সংক্ষিপ্ত বিবরণ দেখুন',
        proceed_to_checkout: 'অগ্রসর হন',
        select_your_date_and_time: 'আপনার তারিখ ও সময় নির্বাচন করুন',
        done: 'সম্পন্ন',
        require_prescription:
            'এই ঔষধটি নির্দেশিকা প্রয়োজন। অনুগ্রহ করে আপনার প্রেসক্রিপশন আপলোড করুন।',
        regular_delivery_note:
            'রেগুলার (২৪-৪৮ ঘন্টা) ডেলিভারি অপশন রয়েছে এই আইটেমটির জন্য।\nযদি আপনি এই অর্ডারটি এক্সপ্রেস (১২-২৪ ঘণ্টা) ডেলিভারি টাইমের মধ্য পেতে চান দয়া করে এই আইটেমটি ডিলেট ক রুন অথবা এই আইটেমের সামঞ্জস্য অন্য কোন আইটেম যোগ করুন যাতে *Express মার্ক রয়েছে।',
        express_delivery_note:
            'এই আইটেমের জন্য এক্সপ্রেস (১২-২৪ ঘণ্টা) ডেলিভারি রয়েছে',
        express_delivery: 'এক্সপ্রেস ডেলিভারি',
        regular_delivery: 'নিয়মিত ডেলিভারি',
        rx: 'Rx',
        cancel_requested: 'অনুরোধ বাতিল করা হয়েছে',
        delivery_man: 'ডেলিভারি ম্যান',
        status: 'অবস্থা',
        zone: 'জোন',
        issue_raised: 'সমস্যা উত্থাপিত হয়েছে',
        order_again: 'আবার অর্ডার করুন',
        view_details: 'বিস্তারিত দেখুন',
        order_summary: 'অর্ডার সারাংশ',
        after_you_pay_online:
            'আপনি অনলাইন পেমেন্ট করার পর, আপনার অর্ডারটি ডেলিভারিতে যাবে ।',
        pay_online: 'অনলাইনে পেমেন্ট করুন',
        or_pay_cash_on_delivery: 'অথবা ডেলিভারির সময় নগদ প্রদান করুন',
        // Orders
        all: 'All',
        confirmed: 'নিশ্চিত হয়েছে',
        delivering: 'ডেলিভারি হচ্ছে',
        delivered: 'ডেলিভারি হয়েছে',
        there_are_no_orders_yet: 'এখনো কোনো অর্ডার নেই!',
        nothing_found: 'কিছু পাওয়া যায়নি',
        total_discount: 'মোট ছাড়',
        // Single Order
        no_order_found: 'কোনো অর্ডার পাওয়া যায়নি',
        your_cart_is_empty: 'আপনার কার্ট খালি',
        you_havenot_shopped_yet: 'আপনি এখনো কিছু কিনেননি',
        prescription_image: 'Prescription Images',
        additional_info: 'অতিরিক্ত তথ্য লিখুন',
        cashabck_of: 'ক্যাশব্যাক ৳',
        rewarded_for_this_order: 'এই অর্ডারের জন্য পেয়ছেন',
        download_your_invoice: 'আপনার চালান ডাউনলোড করুন',
        do_you_want_to_cancel: 'আপনি কি এই অর্ডারটি বাতিল করতে চান?',
        confirm: 'নিশ্চিত করুন',
        request_failed: 'অনুরোধ ব্যর্থ হয়েছে',
        something_went_wrong_while_loading_your_order:
            'আপনার অর্ডার লোড করতে কিছু সমস্যা হয়েছে, অনুগ্রহ করে আবার চেষ্টা করুন।',
        go_back: 'ফিরে যান',
        // PaymentOption
        you_can: 'আপনি করতে পারেন',
        // SingleOrderProductItem
        cold_chain_maintained: '* শীতলতা বজায় রাখা হয়েছে',
        packed: 'প্যাক করা হয়েছে',
        waiting: 'অপেক্ষমান',
        // Checkout
        place_order: 'অর্ডার দিন',
        pay_online: 'পে অনলাইন',
        select_your_payment_method: 'আপনার পেমেন্ট পদ্ধতি নির্বাচন করুন',
        you_will_be_given_an_option_to_pay:
            'অর্ডারটি প্যাক করা হয়ে ডেলিভারির জন্য প্রস্তুত হওয়ার পরে আপনার অনলাইনে পেমেন্ট করার একটি অপশন প্রদান করা হবে।',
        // Timeline
        you_can: 'You can',
        or_pay_cash_on_delivery: 'অথবা ডেলিভারির সময় নগদ প্রদান করুন',
        payment_not_yet_received: 'পেমেন্ট এখনো প্রাপ্ত হয়নি, আপনি করতে পারেন',
        for_outside_dhaka_delivery: 'ঢাকার বাইরে ডেলিভারির জন্য',
        here_once_we_received_your_payment:
            'here, once we receive your payment your order will go out for delivery. If we do not receive payment within',
        this_order_will_automatically_be_cancelled:
            'এই অর্ডারটি স্বয়ংক্রিয়ভাবে বাতিল হবে।',
        if_you_have_any_query: 'যদি আপনার কোনো প্রশ্ন থাকে,',
        call_us_on: 'আমাদের কল করুন ',
        phone_number: 16778,
        or: ' or ',
        message_us_on_facebook: 'আমাদের ফেসবুকে মেসেজ করুন',
        order_placed: 'অর্ডার দেওয়া হয়েছে',
        //** Lab test start */
        ltSampleCollect: 'স্যাম্পল পাঠান ',
        ltSearch: 'ল্যাব টেস্ট এবং প্যাকেজ সার্চ করুন',
        ltFrequent: 'ফ্রিকুয়েন্টলি বুকড ল্যাব টেস্ট',
        ltIncludes: 'ইনক্লুডস',
        ltAsKnownAs: 'অন্য নাম',
        ltBookTest: 'বুক টেস্ট',
        ltRemoveTest: 'রিমুভ টেস্ট',
        ltPatient: 'পেসেন্ট',
        ltBookFor: 'বুক ফর',
        ltOff: 'ছাড়',
        ltReportIn: 'রিপোর্ট ইন',
        ltHours: 'ঘন্টা',
        ltBooked: 'বুকড',
        ltTimes: 'বার',
        ltBrowseHealth: 'ব্রাউজ বাই হেলথ কনসার্ন',
        ltPopularPackages: 'পপুলার প্যাকেজেস',
        ltLifeStylePackage: 'লাইফ স্টাইল প্যাকেজেস',
        ltVitalOrgan: 'চেকআপ বেইজড ওন ভাইটাল অর্গানস',
        ltMenCheckup: 'রিকোমেন্ডেড চেকআপ ফর ম্যান',
        ltWomenCheckup: 'রিকোমেন্ডেড চেকআপ ফর ওমেন',
        ltTest: 'টেস্ট',
        ltPackage: 'প্যাকেজ',
        ltDetails: 'ডিটেইলস',
        ltLab: 'ল্যাব',
        ltSampleType: 'স্যাম্পল টাইপ',
        ltTestRequirements: 'টেস্ট রিকোয়ার্মেন্টস',
        ltTubeType: 'টিউব টাইপ',
        ltPackageIncluded: 'প্যাকেজ ইনক্লুডেড',
        ltDescription: 'ডিস্ক্রিপশন',
        ltPlain: 'প্লেইন',
        ltShowMore: 'আরো দেখুন',
        ltRecommndedForYou: 'রিকোমেন্ডেড ফর ইউ',
        ltSuggestion: 'সাজেশন দেখাচ্ছে ',
        ltNothingShow: 'কিছু দেখানোর নেই ! ',
        ltNothingLoad: 'কিছু লোড করার নেই ! ',
        ltMyLabTest: 'ল্যাব টেস্ট',
        ltMyOrders: 'অর্ডারসমূহ',
        ltMyReports: 'রিপোর্টসমূহ',
        ltManagePatients: 'মেনেজ পেসেন্টস',
        ltOrder: 'অর্ডার',
        ltDate: 'তারিখ',
        ltSchedule: 'সিডিউল',
        ltOrderDetails: 'অর্ডার তথ্য',
        ltPatientReports: 'পেসেন্ট রিপোর্টস',
        ltManagePatient: 'মেনেজ পেসেন্ট',
        ltEditPatient: 'পেসেন্ট তথ্য বদলান',
        ltPaid: 'পরিশোধিত',
        ltNotPaid: 'অপরিশোধিত',
        ltCOD: 'প্রদানোত্তর পরিশোধ',
        ltOnlinePayment: 'অনলাইন পেমেন্ট',
        ltNote: 'বিশেষ দ্রষ্টব্য',
        ltSampleCollectionAdderss: 'স্যাম্পল গ্রহণের ঠিকানা',
        ltPaymentDetails: 'অর্থ প্রদানের তথ্য',
        ltSubTotal: 'সাবটোটাল',
        ltDiscountApplied: 'ডিসকাউন্ট প্রয়োগ',
        ltCouponApplied: 'কুপন প্রয়োগ',
        ltAroggaCashApplied: 'আরোগ্য ক্যাশ প্রয়োগ',
        ltRoundingOff: 'রাউন্ডিং অফ',
        ltSampleCollectionCharge: 'স্যাম্পল গ্রহণের চাৰ্জ',
        ltHardCopyCharge: 'হার্ড কপি চাৰ্জ (ঐচ্ছিক)',
        ltYouPaid: 'আপনি পে করেছেন',
        ltYouPay: 'আপনি পে করবেন',
        ltOrderDate: 'অর্ডার তারিখ',
        ltPatientName: 'পেসেন্ট এর নাম',
        ltWeight: 'ওজন',
        ltGender: 'লিঙ্গ',
        ltAge: 'বয়স',
        ltRelationShip: 'সম্পর্ক',
        ltSaveChanges: 'সেভ করুন',
        ltUploadPhoto: 'ছবি আপলোড করুন',
        ltTotalPayable: 'মোট প্রদেয়',
        ltTotal: 'মোট',
        ltProceedToCheckout: 'চেকআউট করুন',
        ltChange: 'বদলান',
        ltAddAddress: 'ঠিকানা যোগ করুন',
        ltCheckout: 'চেকআউট',
        ltSampleCollectionSchdule: 'স্যাম্পল গ্রহণের সিডিউল',
        ltWriteAdditionalInfo: 'তথ্য দিন',
        ltSelectSchedule: 'সিডিউল সিলেক্ট করুন',
        ltHardCopyOfReport: 'রিপোর্ট হার্ড কপি',
        ltAmountToBePaid: 'অর্থ প্ৰদেয়',
        ltPlaceOrder: 'অর্ডার করুন',
        ltCodAvailableInDhaka:
            'ক্যাশ অন ডেলিভারি অপশন শুধুমাত্র ঢাকায় প্রদানযোগ্য',
        ltHardCopyDeclaimer:
            'রিপোর্ট ৩-৪ কার্যদিবসের মধ্যে বিতরণ করা হবে। একবার রিপোর্ট পাঠানো হলে হার্ড কপি চার্জ ফেরতযোগ্য নয়',
        ltCongratulations: 'অভিনন্দন',
        ltOrderRecived: 'আপনার অর্ডার সফলভাবে গৃহীত হয়েছে',
        ltStartNewOrder: 'নতুন অর্ডার করুন',
        ltCancelBooking: 'অর্ডার কেন্সেল করুন',
        ltPayNow: 'পরিশোধ করুন',
        //** Lab test end */
        // HomeHeader
        wholesale: 'পাইকারি',
        loading: 'লোড হচ্ছে',
        choose_address: 'ঠিকানা নির্বাচন করুন',
        search_for: 'অনুসন্ধান করুন',
        medicine: 'ঔষধ',
        healthcare_items: 'স্বাস্থ্যসেবা সামগ্রী',
        wellness: 'সুস্থতা',
        // ProductDetails
        show_more: 'আরো দেখুন ',
        show_less: 'সংক্ষিপ্ত দেখুন',
        express_available: 'এক্সপ্রেস প্রেরণ',
        buy_drugs_at_wholesale_price:
            'আপনার ফার্মেসির জন্য পাইকারি দামে ওষুধ কিনতে রেজিষ্ট্রেশন করুন',
        register: 'নিবন্ধন করুন',
        people_recently_viewed_this: 'সাম্প্রতিক মানুষেরা এটা দেখেছেন',
        original_product: '১০০% অসল পণ্য',
        off: 'off',
        brand: 'ব্র্যান্ড',
        generic: 'সাধারণ:',
        choose: 'পছন্দ করুন',
        additional_offers: 'অতিরিক্ত অফার',
        alternative_brands_for: 'বিকল্প ব্র্যান্ড',
        sort: 'সাজানো',
        price: 'মূল্য',
        relevance: 'প্রাসঙ্গিক',
        medicine_overview: 'ওষুধের সংক্ষিপ্ত পরিদর্শন',
        quick_tips: 'দ্রুত পরামর্শ',
        brief_description: 'বর্ণনা',
        faqs: 'প্রতিনিধি প্রশ্নগুলি',
        disclaimer: 'দাবিত্যাগ',
        the_information_provided_herein:
            'এখানে প্রদত্ত তথ্যগুলি সঠিক, আধুনিক এবং পূর্ণমানে সম্পর্কিত সঙ্গীতে সরবরাহ করা হয়েছে কোম্পানির সর্বোত্তম অনুশাসন অনুযায়ী। ',
        please_note_that_this_information:
            '  এই তথ্যটি শারীরিক চিকিৎসা পরামর্শ বা পরামর্শের বিকল্প হিসাবে প্রস্তুত হতে পারে না। আমরা প্রদত্ত তথ্যের সঠিকতা এবং পূর্ণতা নিশ্চিত করতে গ্যারান্টি দেই না। কোন ঔষধ নির্দেশনা এবং/অথবা বিজ্ঞপ্তির অনুপস্থিতি কোম্পানির শর্তাবলীর শঙ্কা হিসাবে গণ্য এবং মনে করা হবে না। আমরা উল্লেখিত তথ্য থেকে উত্থিত পরিণামের দায়ভার গ্রহণ করি না ।',
        visit_store: 'স্টোর পরিদর্শন করুন',
        view_cart: 'কার্ট দেখুন',
        add_to_cart: 'কার্টে যুক্ত করুন',
        requesting: 'অনুরোধ করা হচ্ছে',
        request_sent: 'অনুরোধ করা হয়েছে',
        request_stock: 'স্টকের অনুরোধ',
        select_quantity: 'পরিমাণ নির্বাচন করুন',
        added_to_your_cart: 'আপনার কার্টে যুক্ত হয়েছে',
        favorites: 'প্রিয়',
        how_does_arogga_collect_medicine: 'আরোগ্য কিভাবে ঔষধ সংগ্রহ করে?',
        counterfeit_and_substandard_medicines_are_a_big_problem:
            'নকল এবং মানহীন ঔষধ বাংলাদেশের জন্য একটি বড় সমস্যা, তাই এই সমস্যা কাটিয়ে উঠার জন্য আমাদের সকল ঔষধ ক্রয় করা হয় সরাসরি কোম্পানি থেকে।\n\nআরোগ্য কোন পাইকারি বিক্রেতা থেকে ঔষধ সংগ্রহ করেনা, সুতরাং আমাদের স্টকে থাকা ঔষধ নকল হওয়ার কোন সুযোগ নেই।\n\nযেহেতু প্রতিটি ঔষধ সরাসরি ফার্মাসিউটিক্যাল কোম্পানি থেকেই আসছে,  তাই আমাদের থেকে ক্রয়কৃত ঔষধ নিয়ে আপনি শতভাগ নিশ্চিত থাকতে পারেন৷\n\nঔষধ নকল হওয়ার সুযোগ তখনই থাকে,  যখন কেউ কোম্পানি ব্যাতিত অন্য কোন উৎস থেকে ঔষধ সংগ্রহ করে।',
        prescription_required: 'প্রেসক্রিপশন প্রয়োজন',
        this_medicine_requires_prescription:
            'এই ঔষধের জন্য প্রেসক্রিপশন প্রয়োজন। অনুগ্রহ করে আপনার প্রেসক্রিপশন আপলোড করুন।',
        request_for_medicine: 'ঔষধের জন্য রিকুয়েষ্ট করুন',
        sorry_the_product_is_not_in_our_stock:
            'দুঃখিত পণ্যটি এই মুহুর্তে আমাদের স্টকে নেই, আপনি চাইলে পন্যটির জন্য রিকুয়েষ্ট করতে পারেন। Request Stock বাটনে ক্লিক করে।\n\nসেক্ষেত্রে পন্যটি যখনই স্টকে আসবে আপনাকে নোটিফিকেশনের মাধ্যমে জানানো হবে।',
        this_product_uses_heat_sensitive_boxes:
            'এই পণ্যটি পরিবহনে আরোগ্য তাপ সংবেদনশীল বক্স ব্যবহার করে ',
        this_product_will_be_delivered_in_Dhaka_city_only:
            'এই পণ্যটি শুধুমাত্র ঢাকা শহরে ডেলিভারি হবে',
        this_product_can_be_ordered_from_all_over_bangladesh:
            'এই পণ্যটি সারা বাংলাদেশ থেকে অর্ডার করা যাবে',

        // MyAccount
        my_account: 'আমার অ্যাকাউন্ট',
        notification: 'নোটিফিকেশন',
        notification_details: 'নোটিফিকেশন বিবরণ',
        my_order: 'আমার অর্ডার',
        product_reviews: 'প্রোডাক্ট রিভিউ',
        rider_review: 'রাইডার রিভিউ',
        my_prescriptions: 'আমার প্রেসক্রিপশন',
        request_medicine: 'ঔষধের জন্য রিকুয়েষ্ট করুন',
        my_favorite: 'আমার প্রিয় পন্য',
        manage_address: 'ঠিকানা পরিচালনা করুন',
        payment_history: 'পেমেন্টের ইতিহাস',
        refer_and_earn: 'রেফার করুন এবং উপার্জন করুন',
        rate_us: 'আমাদের ব্যাপারে আপনার মতামত দিন',
        terms_and_conditions: 'শর্তাবলী',
        privacy_policy: ' গোপনীয়তা নীতি ',
        payment_terms: 'পরিশোধের শর্ত',
        faq: 'প্রতিনিধি প্রশ্ন',
        about_us: 'আমাদের সম্পর্কে জানুন',
        contact_us: 'যোগাযোগ করুন',
        my_profile: 'আমার প্রোফাইল',
        sign_in_with_icon: 'সাইন ইন করুন →',
        view_profile: 'প্রোফাইল দেখুন',
        arogga_cash: 'আরোগ্য ক্যাশ: ',
        call_for_order: 'অর্ডারের জন্য কল করুন',
        legal_and_support: 'আইনি সহায়তা',
        sign_out: 'সাইন আউট করুন',
        are_you_sure_you_want_to_sign_out:
            'আপনি কি নিশ্চিত যে আপনি সাইন আউট করতে চান?',
        something_went_wrong_try_again_later: 'আবার চেষ্টা করুন',
        app_camera_permission: 'অ্যাপ ক্যামেরা অনুমতি',
        app_needs_access_to_your_camera: 'আপনার ক্যামেরাতে অ্যাক্সেস প্রয়োজন',
        ask_me_later: 'পরে আবার জিজ্ঞাসা করুন',
        camera_permission_required: 'ক্যামেরা অনুমতি প্রয়োজন',
        name: 'নাম',
        date_of_birth: 'জন্ম তারিখ',
        gender: 'লিঙ্গ',
        district: 'জেলা',
        not_found: 'পাওয়া যায়নি',
        phone: 'ফোন নম্বর',
        email: 'ই-মেইল',
        edit_profile: 'প্রোফাইল সম্পাদনা করুন',
        return_and_refund_policy: ' ফেরৎ এবং পরিশোধ নীতি',
        health_tips: 'স্বাস্থ্য পরামর্শ',
        // ImageGallery
        prescription_downloaded_successfully:
            'প্রেসক্রিপশন সফলভাবে ডাউনলোড হয়েছে',
        permission_required: 'অনুমতি প্রয়োজন',
        storage_permission: 'স্টোরেজ অনুমতি প্রয়োজন',
        storage_permission_is_required: 'স্টোরেজ অনুমতি প্রয়োজন',
        ask_me_later: 'পরে আবার জিজ্ঞাসা করুন',
        // ImageUploaderSheet
        upload_avatar: 'অবতার আপলোড করুন',
        camera: 'ক্যামেরা',
        library: 'লাইব্রেরি',
        // Header
        notifications: 'নোটিফিকেশন',
        my_orders: 'আমার অর্ডার',
        // MyPrescription
        camera_not_available: 'ক্যামেরা পাওয়া যায় নি',
        something_went_wrong_only: 'কিছু ভুল হয়েছে',
        are_you_sure_to_delete_prescription:
            'আপনি কি নিশ্চিত যে আপনি প্রেসক্রিপশনটি মুছে ফেলতে চান?',
        no_prescription_found: 'কোনো প্রেসক্রিপশন পাওয়া যায়নি',
        tap_to_select: 'নির্বাচন করতে ট্যাপ করুন',
        attach_prescription: 'প্রেসক্রিপশন সংযুক্ত করুন',
        maximum_five_prescription_can_be_selected:
            'সর্বাধিক 5টি প্রেসক্রিপশন নির্বাচন করা যাবে',
        // Prescriptions
        add_prescriptions: 'প্রেসক্রিপশন যোগ করুন',
        no_prescription_selected: 'কোনো প্রেসক্রিপশন নির্বাচিত হয়নি',
        prescriptions: 'প্রেসক্রিপশন',
        your_attached_perscription_will_be_secure:
            'আপনার সংযুক্ত প্রেসক্রিপশন সুরক্ষিত এবং ব্যক্তিগত হবে। এটি পর্যালোচনা করতে কেবল আমাদের ফার্মাসিস্ট ব্যবহার করতে পারবেন',
        valid_prescription_guide: 'বৈধ প্রেসক্রিপশন গাইড',
        include_details_of_doctor_and_patient:
            'ডাক্তার এবং রোগীর বিস্তারিত এবং ক্লিনিক ভিজিট বিবরণ অন্তর্ভুক্ত থাকবে। প্রেসক্রিপশন অনুযায়ী ঔষধ বিতরণ করা হবে।',
        why_upload_the_picture_of_the_prescription:
            'কেন প্রেসক্রিপশনের ছবি আপলোড করবেন?',
        prescription_will_be_secure_and_private:
            'আপনার সংযুক্ত প্রেসক্রিপশন নিরাপদ এবং ব্যক্তিগত হবে শুধুমাত্র আমাদের ফার্মাসিস্ট এটি পর্যালোচনা করবে।',
        your_are_free_from_the_fear_of_losing_prescriptions:
            'প্রেসক্রিপশন হারানোর ভয় থেকে আপনি মুক্ত, আজীবনের জন্য আরোগ্য অ্যাপে আপনি খুজে পাবেন আপনার ডিজিটাল প্রেসক্রিপশন।',
        no_problem_if_you_cannot_understand_doctors_handwriting:
            "ডাক্তারের হাতের লেখা বুঝা না গেলেও কোন সমস্যা নেই, আমাদের 'A' গ্রেড ফার্মাসিস্ট প্রেস্ক্রিপশন দেখে ঔষধ অর্ডারে আপনাকে সহযোগিতা করবে।",
        your_perscription_will_never_be_shared_with_any_third_party:
            'আপনার প্রেসক্রিপশন কখনো তৃতীয় কোন পক্ষের সাথে শেয়ার করা হবে না।',
        according_to_bangladesh_government:
            'বাংলাদেশ সরকারের নিয়ম অনুসারে, কিছু মেডিসিন অর্ডার করার জন্য প্রেসক্রিপশন থাকা বাধ্যতামুলক।',
        gallery: 'গ্যালারি',
        pdf_doc: 'পিডিএফ ডকুমেন্ট',
        // Refer
        no_share_no_care: 'না শেয়ার! না কেয়ার!',
        sorry_you_havenot_share_with_anyone:
            'দুঃখিত আপনি কারো সাথে ভাগাভাগি করেননি! এখন ভাগ করুন এবং আবারো জীবনের জন্য অর্জন করুন',
        share: 'Share',
        arogga_referral_code: 'আরোগ্য রেফারেল কোড',
        order_medicine_at_home_from_arogga:
            'ঔষধ অর্ডার করুন ঘরে বসেই আরোগ্য অ্যাপ থেকে।\nরেফার কোডঃ',
        app_download_link: 'অ্যাপ ডাউনলোড লিংকঃ',
        success: 'সফল হয়েছে',
        request_failed: 'অনুরোধ ব্যর্থ হয়েছে',
        order_medicines_and_healthcare_products_from_the_comfort_of_your_home:
            'ঔষধ এবং হেলথকেয়ার প্রোডাক্ট অর্ডার করুন ঘরে বসেই আরোগ্য অ্যাপ থেকে।।\nআর ডেলিভারি পেয়ে যান ১২-৪৮ ঘন্টার মধ্যে\nরেফার কোডঃ',
        enter_the_above_code_while_logging_in_or_install:
            '\nলগিন করার সময় উপরোক্ত কোডটি প্রবেশ করুন অথবা নিচের লিংক থেকে আরোগ্য অ্যাপ ইন্সটল করুন।',
        invite_friends_earn_money: 'বন্ধুদের আমন্ত্রণ করুন। অর্থ উপার্জন করুন।',
        tell_a_friend_about_arogga_and_get:
            'আরোগ্য সম্পর্কে একজন বন্ধুকে জানান এবং',
        taka: 'টাকা',
        reward: 'পুরস্কার',
        your_referral_code: 'আপনার রেফারেল কোড:',
        enter_refer_code: 'রেফারেন্স কোড লিখুন',
        redeem: 'প্রাপ্য',
        share_with_friends: 'বন্ধুদের সাথে শেয়ার করুন',
        you_will_get: 'আপনি পাবেন',
        taka_each_time_your_friends_join_with_your_referral_code:
            'আপনার বন্ধুরা আপনার রেফারেল কোড লিখে আরোগ্যে সাইন আপ করে প্রথম অর্ডার দেওয়ার সময়, তখন আপনি টাকা পাবেন।',
        your_referral_code_is_valid_for_lifetime:
            'আপনার রেফারেল কোড আজীবনের জন্য বৈধ থাকবে',
        // PharmacyRegistration
        pharmacy_registration: 'ফার্মেসি রেজিস্ট্রেশন',
        b2b_registration: 'বি২বি রেজিস্ট্রেশন',
        full_name: 'পুরো নাম',
        enter_full_name: 'পুরো নাম দিন',
        mobile_number: 'মোবাইল নাম্বার',
        enter_mobile_number: 'মোবাইল নাম্বার দিন',
        pharmacy_name: 'ফার্মেসির নাম',
        others_name: 'অন্যান্য নাম',
        enter_your_pharmacy_name: 'আপনার ফার্মেসির নাম দিন',
        enter_your_business_name: 'আপনার ব্যবসার নাম দিন',
        drug_license_number: 'ড্রাগ লাইসেন্স নাম্বার',
        trade_license_number: 'ট্রেড লাইসেন্স নাম্বার',
        enter_your_drug_license_number: 'ড্রাগ লাইসেন্স নাম্বার দিন',
        enter_your_trade_license_number: 'ট্রেড লাইসেন্স নাম্বার দিন',
        upload_drug_license: 'ড্রাগ লাইসেন্স আপলোড করুন',
        upload_trade_license: 'ট্রেড লাইসেন্স আপলোড করুন',
        submit: 'সাবমিট',
        all_the_fields_are_required: 'সমস্ত ক্ষেত্রগুলি প্রয়োজন',
        is_required: 'প্রয়োজন',
        invalid_mobile_number: 'মোবাইল নম্বর বৈধ নয়',
        successful: 'সফল হয়েছে',
        failed: 'ব্যর্থ হয়েছে',
        my_profile: 'আমার প্রোফাইল',
        // Edit Profile
        update_profile: 'প্রোফাইল আপডেট করুন',
        gender: 'লিঙ্গ',
        select_gender: 'লিঙ্গ নির্বাচন করুন',
        date_of_birth: 'জন্ম তারিখ',
        save_changes: 'সেভ করুন',
        male: 'পুরুষ',
        female: 'নারী',
        date_picker: 'তারিখ নির্বাচন',
        profile_updated_successfully: 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
        please_enter_a_valid_email_address: 'একটি বৈধ ইমেল লিখুন',
        type_name_at_least_three_characters:
            'কমপক্ষে ৩ টি অক্ষরের নাম টাইপ করুন',
        // Brand
        brand_list: 'ব্র্যান্ড তালিকা',
        no_brand_available: 'কোন ব্র্যান্ড পাওয়া যায়নি',
        there_are_no_brands_available: 'কোন ব্র্যান্ড পাওয়া যায়নি',
        // SuggestMediciine
        reqeust_medicine: 'ঔষধের অনুরোধ করুন',
        medicine_name: 'ঔষধের নাম',
        enter_medicine_name: 'ঔষধের নাম লিখুন',
        strength: 'শক্তি',
        strength_sign: 'অর্থাৎ ১০ মিলিগ্রাম',
        medicine_form: 'ঔষধের ফর্ম',
        medicine_form_sign: 'i.e ট্যাবলেট',
        company: 'কোম্পানি',
        company_sign: 'i.e স্কয়ার ফার্মাসিউটিক্যালস লিমিটেড',
        upload_file: 'ফাইল আপলোড করুন',
        optional: 'ঐচ্ছিক',
        if_you_want_to_suggest_multiple_medicines:
            'আপনি যদি একাধিক পণ্য সুপারিশ করতে চান, তাহলে ইমেইলে Excel শীট পাঠান -info@arogga.com',
        suggest: 'পরামর্শ দিন',
        name_strength_and_form_are_requierd:
            'পণ্যের নাম এবং প্রকার প্রয়োজনীয়',
        product_name_is_required: 'পণ্যের নাম প্রয়োজন',
        product_suggested: 'প্রস্তাবিত পণ্য',
        medicine: 'ওষুধ',
        beauty: 'সৌন্দর্য',
        healthcare: 'স্বাস্থ্যসেবা',
        product_name: 'পণ্যের নাম',
        enter_product_name: 'পণ্যের নাম লিখুন',
        type: 'Type',
        select_product_type: 'পণ্যের প্রকার নির্বাচন করুন',
        form: 'পণ্যের ধরণ নির্বাচন করুন',
        select_company_name: 'কোম্পানির নাম নির্বাচন করুন',
        enter_medicine_name: 'ঔষধের নাম লিখুন',
        // Help
        hi_what_can_we_help_you_with: 'আমরা আপনাকে কীভাবে সাহায্য করতে পারি?',
        faqs: 'প্রতিনিধি প্রশ্নগুলি',
        for_more_info_call_now: 'আরও তথ্যের জন্য এখনই কল করুন',
        // Blogs
        health_tips_details: 'স্বাস্থ্য পরামর্শের বিস্তারিত',
        read_more: 'আরো পড়ুন',
        // SingleBlog
        share_this_tips_wth_friends: 'এই টিপসগুলি বন্ধুদের সাথে শেয়ার করুন',
        recommended_topics: 'প্রস্তাবিত বিষয়গুলি',
        leave_a_comment: 'মন্তব্য করুন',
        comment: 'মন্তব্য',
        share_your_thoughts: 'আপনার মতামত শেয়ার করুন',
        comments: 'মন্তব্য',
        was_this_post_helpful: 'এই পোস্টটি কি সাহায্যকারী ছিল?',
        share_your_thoughts: 'আপনার মতামত শেয়ার করুন',
        // CategoryListing
        sort_by: 'বাছাই করুন',
        filters: 'ফিল্টার',
        // Addresses
        adddress: 'ঠিকানা',
        current_shipping_address: 'বর্তমান ঠিকানা',
        nothing_more_to_load: 'আর কিছু  নেই!',
        add_new_address: 'নতুন ঠিকানা যোগ করুন',
        delete: 'মুছে ফেলুন',
        manage_address: 'ঠিকানা পরিচালনা করুন',
        // Addaddress
        please_enter_valid_phone_number:
            'একটি বৈধ ১১ ডিজিটের মোবাইল নম্বর লিখুন।',
        enter_your_valid_address: 'আপনার বৈধ ঠিকানা লিখুন',
        add_shipping_address: 'শিপিং ঠিকানা যোগ করুন',
        country_code: '+৮৮',
        region: 'অঞ্চল',
        select_region: 'অঞ্চল নির্বাচন করুন',
        city: 'শহর',
        select_city: 'শহর নির্বাচন করুন',
        area: 'Area',
        select_area: 'এলাকা নির্বাচন করুন',
        type_house_flat_no_road: 'ফ্ল্যাট নম্বর, রাস্তা, লিখুন',
        address_type: 'ঠিকানার ধরণ',
        make_default_address: 'ডিফল্ট ঠিকানা',
        save_address: 'ঠিকানা সংরক্ষণ করুন',
        phone_number_text: 'ফোন নম্বর',
        // ProductListing
        all_products: 'সমস্ত পণ্য',
        products: 'পণ্য',
        cart_products: 'পণ্য',

        // WishList
        tags: 'ট্যাগসমূহ',
        manage_tags_to: 'ট্যাগগুলি পরিচালনা করুন',
        new_tags: 'নতুন ট্যাগ',
        enter_tag_name: 'ট্যাগ নাম লিখুন',
        add_tag: 'ট্যাগ যোগ করুন',
        choose_clor_for_this_tag: 'এই ট্যাগের জন্য রঙ সিলেক্ট করুন:',
        this_product_is_already_tagged: 'এই পণ্যটি ইতিমধ্যে ট্যাগ করা হয়েছে',
        no_favorite_yet: 'এখনো কোনো ইচ্ছেতালিকা নেই',
        you_havent_marked_any_favorite:
            'আপনি ইচ্ছাতালিকায় কোনো আইটেম চিহ্নিত করেননি',
        there_are_no_tags_on_this_product: 'এই পণ্যে কোনো ট্যাগ নেই!',
        other_tag: 'অন্যান্য ট্যাগ:',
        tag_name_should_be_at_least_two_characters:
            'ট্যাগের নাম অন্তত ২ টি অক্ষর হতে হবে',
        are_you_sure_to_remove_this_item_from_wishlist:
            'আপনি কি নিশ্চিত যে আপনি ইচ্ছাতালিকা থেকে এই আইটেমটি মুছে ফেলতে চান?',
        // CompanyList
        search_company: 'কোম্পানি অনুসন্ধান করুন',
        // HomeCategoryModal
        categories: 'তালিকা সমূহ',
        top_brands: 'শীর্ষ ব্র্যান্ড',
        shop_by_categories: 'তালিকা দ্বারা কেনাকাটা',
        general_discount: 'সাধারণ ছাড়',
        cancelled: 'বাতিল',
        total_additions: 'মোট সংযোজন',
        // mixed
        go_to_home: 'হোম এ ফিরে যান',
        sorry_we_can_not_find_your_orders:
            'দুঃখিত! আমরা আপনার অর্ডারটি খুঁজে পাচ্ছি না!',
        // Vendor
        no_product_is_available: 'পণ্য সরবরাহ নেই',
        product_list: 'পণ্য তালিকা:',
        purchase_order_list: 'ক্রয় আদেশ তালিকা',
        purcase_order_id: ' ক্রয় অর্ডার আইডি:',
        upload_prescription: 'প্রেসক্রিপশন আপলোড করুন',
        upload_profile_photo: 'প্রোফাইল ফটো আপলোড করুন',
        special_offers: 'বিশেষ অফার',
        we_will_notify_you: 'আমরা আপনাকে অবহিত করব!',
        added_successfully: 'সফলভাবে যুক্ত করা হয়েছে!',
        you_already_requested_this_product:
            'আপনি ইতিমধ্যে এই পণ্য অনুরোধ করেছেন!',
        orders: 'অর্ডার',
        notified_products: 'বিজ্ঞপ্তিকৃত পণ্য',
        suggested_products: 'প্রস্তাবিত পণ্য',
        wishlist: 'ইচ্ছেতালিকা',
        labtest: 'ল্যাব টেষ্ট',
        vendor_dashboard: 'বিক্রেতার ড্যাশবোর্ড',
        transaction_history: 'লেনদেনের ইতিহাস',
        logout: 'লগআউট',
        we_are_hiring: 'আমরা নিয়োগ করছি',
        all_brand: 'সমস্ত ব্র্যান্ড',
        select_address: 'ঠিকানা নির্বাচন করুন',
        proceed_to_checkout: 'চেকআউটে অগ্রসর হোন',
        date: 'তারিখ',
        subarea: 'Sub area',
        notify: 'অবহিত করুন',
        all_products: 'সমস্ত পণ্য',
        you_didnot_request_any_products: 'আপনি কোনো পণ্য অনুরোধ করেননি!',
        this_product_is_not_available_right_now:
            'এই পণ্যটি এখন উপলব্ধ নয়। পণ্যটি উপলব্ধ হলে আমরা আপনাকে অবহিত করব।',
        view_requested_items: 'অনুরোধিত আইটেম দেখুন',
        deleted_successfully: 'সফলভাবে মুছে ফেলা হয়েছে',
        currently_this_product_not_available:
            'বর্তমানে এই পণ্য পাওয়া যাচ্ছে না',
        this_product_is_currently_out_of_stock_please:
            'বর্তমানে এই পণ্য স্টকে নেই। পণ্যটি উপলব্ধ হলে আপনাকে অবহিত করতে নিচে ক্লিক করুন!',
        no_product_found: 'কোনো পণ্য পাওয়া যায়নি',
        yay_you_have_seen_it_all: 'হুরে! আপনি সব দেখে ফেলেছেন!',
        replacement_products_for: 'প্রতিস্থান পণ্য',
        no_products_found_for_replacement:
            'প্রতিস্থানের জন্য কোনো পণ্য পাওয়া যায়নি',
        packed: 'প্যাকেজিং করা হয়েছে',
        we_are_waiting_for_this_item_to_be_packed:
            'আমরা এই আইটেমটি প্যাকেজিং করার জন্য অপেক্ষা করছি।',
        this_item_is_already_packe_cannot_be_edited_anymore:
            'এই আইটেমটি ইতিমধ্যে প্যাকেজিং করা হয়েছে, আর সম্পাদনা করা সম্ভব নয়।',
        replace_with_alternative_item: 'বিকল্প পণ্যে প্রতিস্থাপন করুন',
        replace: 'প্রতিস্থাপন করুন',
        are_you_sure_to_delete_this_product:
            'আপনি কি নিশ্চিত যে আপনি এই পণ্যটি মুছে ফেলতে চান',
        product_deleted_successfully: 'পণ্য সফলভাবে মুছে ফেলা হয়েছে!',
        vendor_dashboard: 'বিক্রেতা ড্যাশবোর্ড',
        suggest_products: 'প্রস্তাবিত পণ্য',
        company_name: 'কোম্পানির নাম',
        company_name_example: 'উদাহরণঃ Cerave, স্কয়ার ফার্মাসিউটিক্যালস',
        upload_image: 'ছবি আপলোড করুন',
        medicine_products: 'ওষুধ পণ্য',
        healthcare_products: 'হেলথকেয়ার পণ্য',
        beauty_products: 'বিউটি প্রোডাক্ট',
        address_deleted_successfully: 'ঠিকানা সফলভাবে মুছে ফেলা হয়েছে!',
        confirm_default_address: 'ডিফল্ট ঠিকানা নিশ্চিত করুন',
        are_you_sure_to_make_this_address_default:
            'আপনি কি নিশ্চিত যে আপনি এই ঠিকানাটি ডিফল্ট করতে চান?',
        no_address_found: 'কোনো ঠিকানা পাওয়া যায়নি',
        you_have_not_added_your_address: 'আপনি আপনার ঠিকানা যোগ করেননি',
        no_notification: 'নোটিফিকেশন নেই!',
        we_have_not_any_notification_for_you:
            'আমরা আপনার জন্য কোনো নোটিফিকেশন নেই',
        mark_as_read: 'দেখা হয়েছে',
        notifications_unread: 'নোটিফিকেশনসমূহ দেখা হয়নি',
        suggest_products: 'পণ্য সুপারিশ করুন',
        lab_tests: 'ল্যাব টেস্ট',
        add_up_to_five_mb: 'সর্বোচ্চ ৫ এমবি যোগ করুন',
        verify: 'Verify',
        arogga_cash_applied: 'Arogga Cash Applied',
        arogga_bonus_applied: 'Arogga Bonus Applied',
        app_version: 'App Version',
        log_in_or_register_to_view_your_complete_profile:
            'Log in or Register to view your complete profile',
        no_blogs_found: 'No blogs Found!',
        we_have_not_any_blog_from: 'we haven’t any blog from',
        your_reply_sent_successfully: 'Your Reply sent Successfully!',
        your_comment_sent_successfully: 'Your Comment sent Successfully!',
        new: 'new',
        easily_order_by_your_prescription: 'Easily Order by your prescription',
        upload_your_perscription_picture:
            'upload your prescription pic and we will do the rest',
        trending_product_is_loading: 'Trending product is loading',
        purchase_order_items_list: 'Purchase Order Items List:',
        withdraw_your_fund: 'Withdraw Your Fund',
        please_select_your_withdrawl_method:
            'Please select your withdrawl method to withdraw your fund.',
        product_description: 'Product Description',
        recent_searches: 'Recent Searches',
        clear_recent_searched_items: 'Clear Recent Searched Items',
        are_you_sure_to_clear_recent_searched_items:
            'Are you sure to clear rececnt searched items',
        clear: 'Clear',
        did_not_match_any_medicine:
            ' did not match any medicine, healthcare, beauty products or lab test',
        suggestions: 'Suggestions:',
        make_sure_that_all_words_are_spelled_correctly:
            'Make sure that all words are spelled correctly',
        try_different_keywords: 'Try different keywords',
        try_more_general_keywords: 'Try more general keywords',
        or_capital: 'Or',
        options: ' option.',
        you_can_request_us_to_add_medicine:
            'You can request us to add medicine/healthcare products by',
        your_search: 'Your search',
        showing_suggestions_for: 'Showing suggestions for',
        customer_service_call:
            'Our customer service will call you to confirm your order and payment amount.',
        business_type: 'ব্যবসার ধরন',
        select_business_type: 'ব্যবসার ধরন সিলেক্ট করুন',
        you_may_also_like: 'আপনি আরও যেগুলো পছন্দ করতে পারেন',
        name_is_required: 'Name is required',
    },
});

export {strings};
